services:
  postgres:
    image: postgres:17
    container_name: dojoflow_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dojoflow
    ports:
      - "5433:5432"
    volumes:
      - dojoflow_postgres_data:/var/lib/postgresql/data

volumes:
  dojoflow_postgres_data:
