"""create responsible table

Revision ID: 50af6d17cbd8
Revises: c182012c86cd
Create Date: 2026-06-30 04:54:50.592716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50af6d17cbd8'
down_revision: Union[str, Sequence[str], None] = 'c182012c86cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsible',
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('phone_is_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_responsible_academy_id_academy')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_responsible'))
    )
    op.create_index(op.f('ix_responsible_academy_id'), 'responsible', ['academy_id'], unique=False)
    op.create_index(op.f('ix_responsible_public_id'), 'responsible', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responsible_public_id'), table_name='responsible')
    op.drop_index(op.f('ix_responsible_academy_id'), table_name='responsible')
    op.drop_table('responsible')
    # ### end Alembic commands ###
