"""create address table and add address to student

Revision ID: c182012c86cd
Revises: b2c3d4e5f6a7
Create Date: 2026-06-27 02:11:40.734153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c182012c86cd'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=8), nullable=True),
    sa.Column('street', sa.String(length=160), nullable=True),
    sa.Column('neighborhood', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('complement', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_address_academy_id_academy')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address'))
    )
    op.create_index(op.f('ix_address_academy_id'), 'address', ['academy_id'], unique=False)
    op.create_index(op.f('ix_address_public_id'), 'address', ['public_id'], unique=True)
    op.add_column('student', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_student_address_id'), 'student', ['address_id'], unique=False)
    op.create_foreign_key(op.f('fk_student_address_id_address'), 'student', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_student_address_id_address'), 'student', type_='foreignkey')
    op.drop_index(op.f('ix_student_address_id'), table_name='student')
    op.drop_column('student', 'address_id')
    op.drop_index(op.f('ix_address_public_id'), table_name='address')
    op.drop_index(op.f('ix_address_academy_id'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
