"""create initial tables

Revision ID: c24f905e5067
Revises: 
Create Date: 2026-05-23 02:52:55.488729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24f905e5067'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academy',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('active', 'blocked', name='academystatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academy'))
    )
    op.create_index(op.f('ix_academy_public_id'), 'academy', ['public_id'], unique=True)
    op.create_table('import_batch',
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='importstatus', native_enum=False), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_import_batch_academy_id_academy')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batch'))
    )
    op.create_index(op.f('ix_import_batch_academy_id'), 'import_batch', ['academy_id'], unique=False)
    op.create_index(op.f('ix_import_batch_public_id'), 'import_batch', ['public_id'], unique=True)
    op.create_table('master',
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_master_academy_id_academy')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master'))
    )
    op.create_index(op.f('ix_master_academy_id'), 'master', ['academy_id'], unique=False)
    op.create_index(op.f('ix_master_public_id'), 'master', ['public_id'], unique=True)
    op.create_index(op.f('ix_master_telegram_user_id'), 'master', ['telegram_user_id'], unique=True)
    op.create_table('modality',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_modality_academy_id_academy')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modality')),
    sa.UniqueConstraint('academy_id', 'name', name='uq_modality_academy_id_name')
    )
    op.create_index(op.f('ix_modality_academy_id'), 'modality', ['academy_id'], unique=False)
    op.create_table('student',
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('instagram', sa.String(length=80), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.Enum('male', 'female', name='studentsex', native_enum=False), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_student_academy_id_academy')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student'))
    )
    op.create_index(op.f('ix_student_academy_id'), 'student', ['academy_id'], unique=False)
    op.create_index(op.f('ix_student_public_id'), 'student', ['public_id'], unique=True)
    op.create_table('audit_log',
    sa.Column('academy_id', sa.Integer(), nullable=True),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'import', 'payment_registered', 'payment_allocated', 'notification_sent', 'status_changed', name='auditaction', native_enum=False), nullable=False),
    sa.Column('entity_name', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_audit_log_academy_id_academy')),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], name=op.f('fk_audit_log_master_id_master')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_academy_id'), 'audit_log', ['academy_id'], unique=False)
    op.create_index(op.f('ix_audit_log_master_id'), 'audit_log', ['master_id'], unique=False)
    op.create_index(op.f('ix_audit_log_public_id'), 'audit_log', ['public_id'], unique=True)
    op.create_table('enrollment',
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('modality_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='enrollmentstatus', native_enum=False), nullable=False),
    sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('is_exempt', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_enrollment_academy_id_academy')),
    sa.ForeignKeyConstraint(['modality_id'], ['modality.id'], name=op.f('fk_enrollment_modality_id_modality')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_enrollment_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment')),
    sa.UniqueConstraint('academy_id', 'student_id', 'modality_id', name='uq_enrollment_academy_student_modality')
    )
    op.create_index(op.f('ix_enrollment_academy_id'), 'enrollment', ['academy_id'], unique=False)
    op.create_index(op.f('ix_enrollment_modality_id'), 'enrollment', ['modality_id'], unique=False)
    op.create_index(op.f('ix_enrollment_public_id'), 'enrollment', ['public_id'], unique=True)
    op.create_index(op.f('ix_enrollment_student_id'), 'enrollment', ['student_id'], unique=False)
    op.create_table('import_row',
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('import_batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'imported', 'failed', 'skipped', name='importrowstatus', native_enum=False), nullable=False),
    sa.Column('raw_data', sa.String(length=3000), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_import_row_academy_id_academy')),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], name=op.f('fk_import_row_import_batch_id_import_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_row')),
    sa.UniqueConstraint('import_batch_id', 'row_number', name='uq_import_row_batch_row_number')
    )
    op.create_index(op.f('ix_import_row_academy_id'), 'import_row', ['academy_id'], unique=False)
    op.create_index(op.f('ix_import_row_import_batch_id'), 'import_row', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_import_row_public_id'), 'import_row', ['public_id'], unique=True)
    op.create_table('payment_transaction',
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'pix', 'credit_card', 'debit_card', 'bank_transfer', 'other', name='paymentmethod', native_enum=False), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('received_at', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_payment_transaction_academy_id_academy')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_payment_transaction_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_transaction'))
    )
    op.create_index(op.f('ix_payment_transaction_academy_id'), 'payment_transaction', ['academy_id'], unique=False)
    op.create_index(op.f('ix_payment_transaction_public_id'), 'payment_transaction', ['public_id'], unique=True)
    op.create_index(op.f('ix_payment_transaction_student_id'), 'payment_transaction', ['student_id'], unique=False)
    op.create_table('telegram_conversation_state',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('academy_id', sa.Integer(), nullable=True),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('current_flow', sa.String(length=80), nullable=True),
    sa.Column('current_step', sa.String(length=80), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_telegram_conversation_state_academy_id_academy')),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], name=op.f('fk_telegram_conversation_state_master_id_master')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_conversation_state'))
    )
    op.create_index(op.f('ix_telegram_conversation_state_academy_id'), 'telegram_conversation_state', ['academy_id'], unique=False)
    op.create_index(op.f('ix_telegram_conversation_state_master_id'), 'telegram_conversation_state', ['master_id'], unique=False)
    op.create_index(op.f('ix_telegram_conversation_state_public_id'), 'telegram_conversation_state', ['public_id'], unique=True)
    op.create_index(op.f('ix_telegram_conversation_state_telegram_user_id'), 'telegram_conversation_state', ['telegram_user_id'], unique=True)
    op.create_table('telegram_message_log',
    sa.Column('academy_id', sa.Integer(), nullable=True),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='telegrammessagedirection', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('received', 'sent', 'failed', name='telegrammessagestatus', native_enum=False), nullable=False),
    sa.Column('message_text', sa.String(length=4000), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_telegram_message_log_academy_id_academy')),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], name=op.f('fk_telegram_message_log_master_id_master')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_telegram_message_log_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_message_log'))
    )
    op.create_index(op.f('ix_telegram_message_log_academy_id'), 'telegram_message_log', ['academy_id'], unique=False)
    op.create_index(op.f('ix_telegram_message_log_master_id'), 'telegram_message_log', ['master_id'], unique=False)
    op.create_index(op.f('ix_telegram_message_log_public_id'), 'telegram_message_log', ['public_id'], unique=True)
    op.create_index(op.f('ix_telegram_message_log_student_id'), 'telegram_message_log', ['student_id'], unique=False)
    op.create_index(op.f('ix_telegram_message_log_telegram_user_id'), 'telegram_message_log', ['telegram_user_id'], unique=False)
    op.create_table('payment',
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('reference_month', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'partial', 'paid', 'overdue', 'waived', 'pending_configuration', name='paymentstatus', native_enum=False), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_payment_academy_id_academy')),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment.id'], name=op.f('fk_payment_enrollment_id_enrollment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment')),
    sa.UniqueConstraint('academy_id', 'enrollment_id', 'reference_month', name='uq_payment_academy_enrollment_reference_month')
    )
    op.create_index(op.f('ix_payment_academy_id'), 'payment', ['academy_id'], unique=False)
    op.create_index(op.f('ix_payment_enrollment_id'), 'payment', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_payment_public_id'), 'payment', ['public_id'], unique=True)
    op.create_table('notification',
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.Enum('payment_due_soon', 'payment_overdue', 'monthly_summary', 'general', name='notificationtype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'canceled', name='notificationstatus', native_enum=False), nullable=False),
    sa.Column('message_text', sa.String(length=4000), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_notification_academy_id_academy')),
    sa.ForeignKeyConstraint(['master_id'], ['master.id'], name=op.f('fk_notification_master_id_master')),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_notification_payment_id_payment')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_notification_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_academy_id'), 'notification', ['academy_id'], unique=False)
    op.create_index(op.f('ix_notification_master_id'), 'notification', ['master_id'], unique=False)
    op.create_index(op.f('ix_notification_payment_id'), 'notification', ['payment_id'], unique=False)
    op.create_index(op.f('ix_notification_public_id'), 'notification', ['public_id'], unique=True)
    op.create_index(op.f('ix_notification_student_id'), 'notification', ['student_id'], unique=False)
    op.create_table('payment_allocation',
    sa.Column('academy_id', sa.Integer(), nullable=False),
    sa.Column('payment_transaction_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], name=op.f('fk_payment_allocation_academy_id_academy')),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('fk_payment_allocation_payment_id_payment')),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transaction.id'], name=op.f('fk_payment_allocation_payment_transaction_id_payment_transaction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocation')),
    sa.UniqueConstraint('academy_id', 'payment_transaction_id', 'payment_id', name='uq_payment_allocation_transaction_payment')
    )
    op.create_index(op.f('ix_payment_allocation_academy_id'), 'payment_allocation', ['academy_id'], unique=False)
    op.create_index(op.f('ix_payment_allocation_payment_id'), 'payment_allocation', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_allocation_payment_transaction_id'), 'payment_allocation', ['payment_transaction_id'], unique=False)
    op.create_index(op.f('ix_payment_allocation_public_id'), 'payment_allocation', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_allocation_public_id'), table_name='payment_allocation')
    op.drop_index(op.f('ix_payment_allocation_payment_transaction_id'), table_name='payment_allocation')
    op.drop_index(op.f('ix_payment_allocation_payment_id'), table_name='payment_allocation')
    op.drop_index(op.f('ix_payment_allocation_academy_id'), table_name='payment_allocation')
    op.drop_table('payment_allocation')
    op.drop_index(op.f('ix_notification_student_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_public_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_payment_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_master_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_academy_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_payment_public_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_enrollment_id'), table_name='payment')
    op.drop_index(op.f('ix_payment_academy_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_telegram_message_log_telegram_user_id'), table_name='telegram_message_log')
    op.drop_index(op.f('ix_telegram_message_log_student_id'), table_name='telegram_message_log')
    op.drop_index(op.f('ix_telegram_message_log_public_id'), table_name='telegram_message_log')
    op.drop_index(op.f('ix_telegram_message_log_master_id'), table_name='telegram_message_log')
    op.drop_index(op.f('ix_telegram_message_log_academy_id'), table_name='telegram_message_log')
    op.drop_table('telegram_message_log')
    op.drop_index(op.f('ix_telegram_conversation_state_telegram_user_id'), table_name='telegram_conversation_state')
    op.drop_index(op.f('ix_telegram_conversation_state_public_id'), table_name='telegram_conversation_state')
    op.drop_index(op.f('ix_telegram_conversation_state_master_id'), table_name='telegram_conversation_state')
    op.drop_index(op.f('ix_telegram_conversation_state_academy_id'), table_name='telegram_conversation_state')
    op.drop_table('telegram_conversation_state')
    op.drop_index(op.f('ix_payment_transaction_student_id'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_public_id'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_academy_id'), table_name='payment_transaction')
    op.drop_table('payment_transaction')
    op.drop_index(op.f('ix_import_row_public_id'), table_name='import_row')
    op.drop_index(op.f('ix_import_row_import_batch_id'), table_name='import_row')
    op.drop_index(op.f('ix_import_row_academy_id'), table_name='import_row')
    op.drop_table('import_row')
    op.drop_index(op.f('ix_enrollment_student_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_public_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_modality_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_academy_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_audit_log_public_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_master_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_academy_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_student_public_id'), table_name='student')
    op.drop_index(op.f('ix_student_academy_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_modality_academy_id'), table_name='modality')
    op.drop_table('modality')
    op.drop_index(op.f('ix_master_telegram_user_id'), table_name='master')
    op.drop_index(op.f('ix_master_public_id'), table_name='master')
    op.drop_index(op.f('ix_master_academy_id'), table_name='master')
    op.drop_table('master')
    op.drop_index(op.f('ix_import_batch_public_id'), table_name='import_batch')
    op.drop_index(op.f('ix_import_batch_academy_id'), table_name='import_batch')
    op.drop_table('import_batch')
    op.drop_index(op.f('ix_academy_public_id'), table_name='academy')
    op.drop_table('academy')
    # ### end Alembic commands ###
